### ISSUE TITLE
openscap maint-1.2 fails to build on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by mpreisler** [OpenSCAP/openscap#1250]
I followed instructions in README.md, git HEAD afc2f878f38d8d59e80772a1840e4ecfbb96e93a

The build fails with:
```
  CCLD     probe_selinuxsecuritycontext
  CCLD     probe_rpminfo
  CCLD     probe_rpmverify
  CCLD     probe_rpmverifyfile
  CCLD     probe_rpmverifypackage
/usr/bin/ld: probe_rpmverify-rpmverify.o: undefined reference to symbol 'rpmlogClose'
//usr/usr/bin/ld: probe_rpminfo-/rpminfo.o: undefined reference to symbol 'rpmlogClose'
//usr/lib/x86_64-linux-libgnu/librpmio.so.8: error adding symbols: DSO missing from command line
/x86_64-linux-collect2: error: ld returned 1 exit status
gnu/librpmio.so.8: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:1807: recipe for target 'probe_rpmverify' failed
make[3]: *** [probe_rpmverify] Error 1
make[3]: *** Waiting for unfinished jobs....
Makefile:1803: recipe for target 'probe_rpminfo' failed
make[3]: *** [probe_rpminfo] Error 1
/usr/bin/ld: probe_rpmverifyfile-rpmverifyfile.o: undefined reference to symbol 'rpmlogClose'
//usr/lib/x86_64-linux-gnu/librpmio.so.8: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
/usr/bin/ld: probe_rpmverifypackage-rpmverifypackage.o: undefined reference to symbol 'rpmDefineMacro'
//usr/lib/x86_64-linux-gnu/librpmio.so.8: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:1811: recipe for target 'probe_rpmverifyfile' failed
make[3]: *** [probe_rpmverifyfile] Error 1
Makefile:1815: recipe for target 'probe_rpmverifypackage' failed
make[3]: *** [probe_rpmverifypackage] Error 1
make[3]: Leaving directory '/home/user/d/openscap/src/OVAL/probes'
Makefile:2732: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/user/d/openscap/src/OVAL/probes'
Makefile:1302: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/user/d/openscap'
Makefile:1111: recipe for target 'all' failed
make: *** [all] Error 2
```

Running `apt remove librpm-dev` fixes the issue because RPM probes are no longer built. Perhaps that's what we should recommend our users becuase rpm probes are not very useful on Ubuntu anyway.

**Comment by evgenyz** [comment]
We are not going to release any 1.2.x versions. 1.3.x versions are fine with latest 20.04 LTS. Closing.
